const description = [
	{
		id: 1,
		img: '/src/app/assets/product__img.svg',
		imgFull: '/src/app/assets/product__imgFull.svg',
		title: 'Essence Mascara Lash Princess',
		price: 110,
		quantity: 0,
		sale: 14.5,
		imgSml: '/src/app/assets/product__imgSml.svg',
		deleted: 0,
	},
	{
		id: 2,
		img: '/src/app/assets/product__img.svg',
		imgFull: '/src/app/assets/product__imgFull.svg',
		title: 'Essence Mascara Lash Princess',
		price: 110,
		quantity: 0,
		sale: 14.5,
		imgSml: '/src/app/assets/product__imgSml.svg',
		deleted: 0,
	},
	{
		id: 3,
		img: '/src/app/assets/product__img.svg',
		imgFull: '/src/app/assets/product__imgFull.svg',
		title: 'Essence Mascara Lash Princess',
		price: 110,
		quantity: 0,
		sale: 14.5,
		imgSml: '/src/app/assets/product__imgSml.svg',
		deleted: 0,
	},
	{
		id: 4,
		img: '/src/app/assets/product__img.svg',
		imgFull: '/src/app/assets/product__imgFull.svg',
		title: 'Essence Mascara Lash Princess',
		price: 110,
		quantity: 0,
		sale: 14.5,
		imgSml: '/src/app/assets/product__imgSml.svg',
		deleted: 1,
	},
	{
		id: 5,
		img: '/src/app/assets/product__img.svg',
		imgFull: '/src/app/assets/product__imgFull.svg',
		title: 'Essence Mascara Lash Princess',
		price: 110,
		quantity: 0,
		sale: 14.5,
		imgSml: '/src/app/assets/product__imgSml.svg',
	},
	{
		id: 6,
		img: '/src/app/assets/product__img.svg',
		imgFull: '/src/app/assets/product__imgFull.svg',
		title: 'Essence Mascara Lash Princess',
		price: 110,
		quantity: 0,
		sale: 14.5,
		imgSml: '/src/app/assets/product__imgSml.svg',
	},
	{
		id: 7,
		img: '/src/app/assets/product__img.svg',
		imgFull: '/src/app/assets/product__imgFull.svg',
		title: 'Essence Mascara Lash Princess',
		price: 110,
		quantity: 0,
		sale: 14.5,
		imgSml: '/src/app/assets/product__imgSml.svg',
	},
	{
		id: 8,
		img: '/src/app/assets/product__img.svg',
		imgFull: '/src/app/assets/product__imgFull.svg',
		title: 'Essence Mascara Lash Princess',
		price: 110,
		quantity: 0,
		sale: 14.5,
		imgSml: '/src/app/assets/product__imgSml.svg',
	},
	{
		id: 9,
		img: '/src/app/assets/product__img.svg',
		imgFull: '/src/app/assets/product__imgFull.svg',
		title: 'Essence Mascara Lash Princess',
		price: 110,
		quantity: 0,
		sale: 14.5,
		imgSml: '/src/app/assets/product__imgSml.svg',
	},
	{
		id: 10,
		img: '/src/app/assets/product__img.svg',
		imgFull: '/src/app/assets/product__imgFull.svg',
		title: 'Essence Mascara Lash Princess',
		price: 110,
		quantity: 0,
		sale: 14.5,
		imgSml: '/src/app/assets/product__imgSml.svg',
	},
	{
		id: 11,
		img: '/src/app/assets/product__img.svg',
		imgFull: '/src/app/assets/product__imgFull.svg',
		title: 'Essence Mascara Lash Princess',
		price: 110,
		quantity: 0,
		sale: 14.5,
		imgSml: '/src/app/assets/product__imgSml.svg',
	},
	{
		id: 12,
		img: '/src/app/assets/product__img.svg',
		imgFull: '/src/app/assets/product__imgFull.svg',
		title: 'Essence Mascara Lash Princess',
		price: 110,
		quantity: 0,
		sale: 14.5,
		imgSml: '/src/app/assets/product__imgSml.svg',
	},
]

export { description }
