export { Home } from './Home/Home'
export { OneProduct } from './OneProduct/OneProduct'
export { Cart } from './Cart/Cart'
export { NotFound } from './NotFound/NotFound'
export { Login } from './Login/Login'
