export { Header } from './Header/Header'
export { Hero } from './Hero/Hero'
export { Catalog } from './Catalog/Catalog'
export {ProductCard} from './ProductCard/ProductCard'
export {ProductList} from './ProductList/ProductList'
export {FAQ} from './FAQ/FAQ'
export {Footer} from './Footer/Footer'
export {CartList} from './CartList/CartList'
export {CartItem} from './CartItem/CartItem'